Deploy script: write parity creds to backend config; rm Plankton script

diff --git a/kovan/deploy_contracts b/kovan/deploy_contracts
--- a/kovan/deploy_contracts
+++ b/kovan/deploy_contracts
@@ -36,7 +36,7 @@ npm i
 
 ganache-cli --version || npm install -g ganache-cli || { 
   echo -e "${boldred}NPM permissions error.
-Install ganache-cli globally and run this script again.$endcolor"
+Install ganache-cli globally and run this script again.$endcolor";
 }
 
 etherscan="https://kovan.etherscan.io/address/${address}"
@@ -47,3 +47,25 @@ else
   echo -e "${boldred}Deployment failed, see logs above. For any successful contracts, see:
 $etherscan$endcolor";
 fi
+
+# Write to config_local.ini
+pass=`cat pass` || {
+  echo -e "${boldred}Error: can't read password file.$endcolor";
+  exit 1;
+}
+cd ../../backend
+if [ ! -f config_local.ini ]; then
+  cp config.ini config_local.ini;
+fi
+
+sed -i -e "/parity.address =/ s/= .*/= $address/" config_local.ini
+sed -i -e "/parity.password =/ s/= .*/= $pass/" config_local.ini
+sed -i -e "/parity.address1 =/ s/= .*/= $address/" config_local.ini
+sed -i -e "/parity.password1 =/ s/= .*/= $pass/" config_local.ini
+rm config_local.ini-e
+
+cd ../frontend/src/app/pages/home
+
+sed -i -e "/publisher: string =/ s/= .*/= \"$address\"/" types.ts
+rm types.ts-e
+
